package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/whpearson/todo-client/client/todos"
)

// Default simple to do list HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new simple to do list HTTP client.
func NewHTTPClient(formats strfmt.Registry) *SimpleToDoList {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("localhost", "/", []string{"http", "https"})
	return New(transport, formats)
}

// New creates a new simple to do list client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *SimpleToDoList {
	cli := new(SimpleToDoList)
	cli.Transport = transport

	cli.Todos = todos.New(transport, formats)

	return cli
}

// SimpleToDoList is a client for simple to do list
type SimpleToDoList struct {
	Todos *todos.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *SimpleToDoList) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Todos.SetTransport(transport)

}
